# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Run ls after every cd
cd(){
	if [ -n "$1" ];
	then
		builtin cd "$@" && ls
	else
		builtin cd ~ && ls
	fi
}
alias ytdl="youtube-dl --extract-audio --audio-format=mp3 -l"
alias gs="git status"
alias term1="rdesktop -g 1000x1000 nws-term1.nws.oregonstate.edu"

export WORKON_HOME=$HOME/.virtualenvs
source $HOME/.virtualenvwrapper

alias ch="cd ~/Code/chili && workon zamboni"
alias chshell="./manage.py shell_plus"

alias zpull="z && git checkout master && git pull && git submodule update && git submodule --quiet foreach 'git submodule --quiet sync && git submodule update --init --recursive'"
alias zup='zpull && ./vendor/src/schematic/schematic migrations'
alias zmkt="./manage.py runserver --settings=slm 8080"
alias zamo="./manage.py runserver --settings=sla 8080"
alias zmktlocal="./manage.py runserver --settings=slml 8080"
alias zindex="./manage.py cron index_latest_stats"
alias zindexall="./manage.py cron index_latest_stats && ./manage.py index_stats"
alias zsql="mysql -h 10.22.70.21 -u root remora"
alias zshell="./manage.py shell_plus --settings=slm"
alias zshelllocal="./manage.py shell_plus --settings=slml"
alias zcheckers="./manage.py index_mkt_stats --addons 364740 --settings=slm"
alias zreindex="./manage.py cron reindex_addons"

alias z='cd ~/Code/zamboni && workon zamboni'
alias zstats="cd ~/Code/zamboni/mkt/stats"
alias zjs="cd ~/Code/zamboni/media/js/"
alias zimpala="cd ~/Code/zamboni/media/js/impala/stats"
alias zappstats="cd ~/Code/zamboni/apps/stats"
alias zaddon="cd ~/Code/zamboni/apps/addons"
alias zwebapp="cd ~/Code/zamboni/mkt/webapps"
alias zdev="cd ~/Code/zamboni/mkt/developers"
alias zdevtemp="cd ~/Code/zamboni/mkt/developers/templates/developers/payments/includes"
alias zratings="cd ~/Code/zamboni/mkt/ratings"
alias zmktdir="cd ~/Code/zamboni/mkt"
alias zbrowse="cd ~/Code/zamboni/mkt/browse"
alias ztheme="cd ~/Code/zamboni/mkt/themes"
alias zcss="cd ~/Code/zamboni/media/css"
alias zprq="cd ~/Code/zamboni/mkt/reviewers"
alias zprqtemp="cd ~/Code/zamboni/mkt/reviewers/templates/reviewers/themes"
alias zconst="vim ~/Code/zamboni/apps/constants/base.py"
alias openvpn="sudo /etc/init.d/openvpn restart"
alias zshell="./manage.py shell_plus --settings=slm"
alias zshelllocal="./manage.py shell_plus --settings=slml"

alias a="ssh aws"
alias c="cd"
alias l="ls"
alias v="vim"
alias box="cd ~/Code/grandbox"
alias utg="cd ~/Code/underthegun"
